# Generated by Django 5.2.5 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=120),
        ),
    ]
