# Generated by Django 5.2.5 on 2025-09-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='planned', max_length=20)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('completed', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='core.artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concerts', to='core.venue')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='conciertos.tour')),
            ],
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=50)),
                ('is_cover', models.BooleanField(default=False)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_entries', to='conciertos.concert')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciertos.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('concert', 'position')},
            },
        ),
    ]
