# Generated by Django 5.2.5 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciertos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
