# Generated by Django 5.2.5 on 2025-10-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciertos', '0002_concert_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
