# Generated by Django 5.2.5 on 2025-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciertos', '0003_song_original_artist_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setlistentry',
            constraint=models.UniqueConstraint(fields=('concert', 'song'), name='unique_concert_song'),
        ),
    ]
