# Generated by Django 5.2.5 on 2025-09-14 23:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conciertos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('favorite_concerts', models.ManyToManyField(blank=True, to='conciertos.concert')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='conciertos.concert')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='fans.fan')),
            ],
            options={
                'unique_together': {('fan', 'concert')},
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='conciertos.concert')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='fans.fan')),
            ],
            options={
                'unique_together': {('fan', 'concert')},
            },
        ),
    ]
