# Generated by Django 5.2.5 on 2025-10-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0002_fan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='user',
        ),
    ]
